"""add_llm_session_fields

Revision ID: b22c95c8ddf5
Revises: a3f1c8d9e2b4
Create Date: 2026-06-01 17:38:41.386011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b22c95c8ddf5'
down_revision: Union[str, None] = 'a3f1c8d9e2b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_sessions', sa.Column('conversation_history', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('chat_sessions', sa.Column('questions_asked', sa.Integer(), nullable=False, server_default=sa.text('0')))
    op.add_column('chat_sessions', sa.Column('final_diagnosis', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_sessions', 'final_diagnosis')
    op.drop_column('chat_sessions', 'questions_asked')
    op.drop_column('chat_sessions', 'conversation_history')
    # ### end Alembic commands ###
